development:
  url: postgresql://postgres:postgres@0.0.0.0:5432/stacklike-backend_dev

test:
  url: postgresql://postgres:postgres@0.0.0.0:5432/stacklike-backend_test

production:
  url: <%= ENV['STACKLIKE-BACKEND_DATABASE_URL'] %>
